openapi: 3.0.0
info:
  title: Services Service API
  version: 1.0.0
paths:
  /api/services/create:
    post:
      summary: Create a new service
      requestBody:
        description: Service data for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateServiceRequest'
      responses:
        '200':
          description: Service created successfully
          content:
            application/json:
              schema:
                type: integer
                format: int32
                description: The unique identifier of the created service.
        '400':
          description: Bad request, invalid data provided

  /api/services:
    get:
      summary: Get all services
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
        '404':
          description: Services not found

  /api/services/{orderId}:
    get:
      summary: Get services by order ID
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInOrderResponse'
        '404':
          description: Services not found

components:
  schemas:
    CreateServiceRequest:
      type: object
      properties:
        Title:
          type: string
          description: The title of the service.
        Category:
          type: string
          description: The category of the service.
        Description:
          type: string
          description: The description of the service.
        Price:
          type: number
          format: decimal
          description: The price of the service.

    ServiceResponse:
      type: object
      properties:
        Id:
          type: integer
          format: int32
          description: The unique identifier of the service.
        Title:
          type: string
          description: The title of the service.
        Category:
          type: string
          description: The category of the service.
        Description:
          type: string
          description: The description of the service.
        Price:
          type: number
          format: decimal
          description: The price of the service.

    ServiceInOrderResponse:
      type: object
      properties:
        ServiceId:
          type: integer
          format: int32
          description: The unique identifier of the service.
        ServiceName:
          type: string
          description: The name of the service.
        ServicePrice:
          type: number
          format: decimal
          description: The price of the service.
